# Generated by Django 6.1.1 on 2026-09-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('unit', models.CharField(default='g', max_length=10, verbose_name='Unidade')),
                ('current_stock', models.FloatField(default=0, verbose_name='Estoque atual')),
                ('min_stock', models.FloatField(default=0, verbose_name='Estoque mínimo')),
                ('cost_per_unit', models.FloatField(verbose_name='Custo por unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Custo')),
                ('category', models.CharField(choices=[('PIZZA', 'Pizza'), ('HAMBURGUER', 'Hambúrguer'), ('DRINK', 'Bebida'), ('DESSERT', 'Sobremesa'), ('SIDE', 'Acompanhamento')], default='PIZZA', max_length=20, verbose_name='Categoria')),
                ('type', models.CharField(choices=[('SIMPLE', 'Simples'), ('PIZZA_HALF', 'Meia Pizza'), ('PIZZA_QUARTER', 'Pizza em 1/4'), ('COMBO', 'Combo')], default='SIMPLE', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagem (URL)')),
                ('preparation_time', models.PositiveIntegerField(default=15, verbose_name='Tempo de preparo (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('unit', models.CharField(default='g', max_length=10, verbose_name='Unidade')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='catalog.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Ingrediente do produto',
                'verbose_name_plural': 'Ingredientes do produto',
            },
        ),
    ]
