# Generated by Django 6.1.1 on 2026-09-17 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('entity', models.CharField(max_length=100, verbose_name='Entidade')),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da entidade')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('type', models.CharField(choices=[('DELIVERY', 'Entrega'), ('TAKEAWAY', 'Retirada'), ('TABLE', 'Mesa')], default='DELIVERY', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Preparando'), ('READY', 'Pronto'), ('DELIVERING', 'Saiu para entrega'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT_CARD', 'Cartão de débito'), ('PIX', 'Pix'), ('IFOOD', 'iFood'), ('MEAL_TICKET', 'Vale-refeição')], default='CASH', max_length=20, verbose_name='Forma de pagamento')),
                ('total', models.FloatField(verbose_name='Total')),
                ('discount', models.FloatField(default=0, verbose_name='Desconto')),
                ('delivery_fee', models.FloatField(default=0, verbose_name='Taxa de entrega')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.FloatField(verbose_name='Preço unitário')),
                ('total_price', models.FloatField(verbose_name='Preço total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('half_flavors', models.TextField(blank=True, null=True, verbose_name='Sabores (meia pizza)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
